// vue-app/src/components/FileInput.vue
<template>
  <form ref="formRef" @submit="onSubmit">
    <label>
      选择上传文件:
      <input type="file" id="file" ref="inputRef"/>
    </label>
    <button type="submit">上传</button>
  </form>
</template>

<script lang="ts" setup>
import { unref, ref } from 'vue';

const inputRef = ref<HTMLInputElement | null>(null);
const formRef = ref<HTMLFormElement | null>(null);

const emit = defineEmits(['click-upload']);

function onSubmit(e: Event) {
  e.preventDefault();

  const inputRefDom = unref(inputRef);
  const file = inputRefDom?.files?.[0];
  emit('click-upload', file);
}
</script>

<style scoped>
</style>

// react-app/src/FileInput.tsx
import * as React from "react";

export type FileInputProps = {
    onUploadFile?: (file?: File) => void;
}

class FileInput extends React.Component<FileInputProps> {
    private readonly fileInput: React.RefObject<HTMLInputElement>;

    constructor(props: any) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);
        this.fileInput = React.createRef();
    }

    componentDidMount() {
    }
    componentWillUnmount() {
    }

    handleChange(selectorFiles: FileList) {
        console.log(selectorFiles);
    }

    handleSubmit(event: any) {
        event.preventDefault();

        const file = this.fileInput.current!.files![0];
        if (this.props.onUploadFile) {
            this.props.onUploadFile(file);
        }
    }

    render() {
        return (
            <form onSubmit={this.handleSubmit}>
                <label>
                    选择上传文件:
                    <input type="file" ref={this.fileInput}/>
                </label>
                <button type="submit">上传</button>
            </form>
        );
    }
}

export default FileInput;
